### ISSUE TITLE
Error Setting up V2 AC

### ISSUE THREAD

**Issue by diedvdyk** [georgezhao2010/midea_ac_lan#10]
I get the following error when I setup my QLIMA AC .
It uses the V2 protocol.
I set Token and Key to None

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/midea_ac_lan/state_manager.py:45
Integration: Midea AC LAN (documentation, issues)
First occurred: 18:08:02 (1 occurrences)
Last logged: 18:08:02

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/midea_ac_lan/config_flow.py", line 112, in async_step_manual
    dm = DeviceManager(user_input[CONF_DEVICE_ID], user_input[CONF_HOST], user_input[CONF_PORT],
  File "/config/custom_components/midea_ac_lan/state_manager.py", line 45, in __init__
    self._token = bytearray.fromhex(token) if token else None
ValueError: non-hexadecimal number found in fromhex() arg at position 0

**Comment by georgezhao2010** [comment]
> 

It's my fault, but how did you to set Token and Key to None? your mean keep the text input empty?
Update to [v0.1.14 ](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.1.14) and try again.

**Comment by georgezhao2010** [comment]
> I get the following error when I setup my QLIMA AC . It uses the V2 protocol. I set Token and Key to None
> 
> This error originated from a custom integration.
> 
> Logger: aiohttp.server Source: custom_components/midea_ac_lan/state_manager.py:45 Integration: Midea AC LAN (documentation, issues) First occurred: 18:08:02 (1 occurrences) Last logged: 18:08:02
> 
> Error handling request Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle resp = await handler(request) File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle result = await result File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper result = await method(view, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step result: FlowResult = await getattr(flow, method)(user_input) File "/config/custom_components/midea_ac_lan/config_flow.py", line 112, in async_step_manual dm = DeviceManager(user_input[CONF_DEVICE_ID], user_input[CONF_HOST], user_input[CONF_PORT], File "/config/custom_components/midea_ac_lan/state_manager.py", line 45, in **init** self._token = bytearray.fromhex(token) if token else None ValueError: non-hexadecimal number found in fromhex() arg at position 0

It's solves your problem?

**Comment by diedvdyk** [comment]
Yes, problem solved. I just setup 2 Airco's.
