### ISSUE TITLE
Unknown error OverflowError('int too big to convert')

### ISSUE THREAD

**Issue by markSms** [georgezhao2010/midea_ac_lan#127]
华凌空调正常接入后，在半个月后离线，日志中包含大量的。
`Unknown error OverflowError('int too big to convert')`

错误消息每隔3秒出现一次

![image](https://user-images.githubusercontent.com/115525130/197549015-ca0906f9-8322-4db1-8e55-81cbc8cd028d.png)

对于日志中报错的位置
![image](https://user-images.githubusercontent.com/115525130/197549211-4f34450d-fe45-4eec-a85f-49591f3d47c7.png)

看日志是device.py的316行抛出的，但是那一行是
`if self.connect(refresh_status=True) is False:`
看上去也没啥问题

一般重启下hass就能恢复

**Comment by georgezhao2010** [comment]
如果能提供调试日志就更好了，这个函数下有调用了很多语句，没法准确定位。

**Comment by markSms** [comment]
@georgezhao2010 谢谢。我当时埋了点，不过等了将近一周才复现。调用堆栈是这样的
```
2022-11-02 10:28:18.310 ERROR (主卧空调) [custom_components.midea_ac_lan.midea.core.device] int too big to convert
Traceback (most recent call last):
  File "/config/custom_components/midea_ac_lan/midea/core/device.py", line 113, in connect
    self.authenticate()
  File "/config/custom_components/midea_ac_lan/midea/core/device.py", line 138, in authenticate
    request = self._security.encode_8370(
  File "/config/custom_components/midea_ac_lan/midea/core/security.py", line 89, in encode_8370
    data = self._request_count.to_bytes(2, "big") + data
OverflowError: int too big to convert
```

**Comment by markSms** [comment]
https://github.com/georgezhao2010/midea_ac_lan/blob/7680f9ae0ec66b8414739ac76802c63011f3329f/custom_components/midea_ac_lan/midea/core/security.py#L79-L94

感觉是90行那个+1不停的加，最后就太大了
