### ISSUE TITLE
2 More questions: Customize entities and set attribute permanently.

### ISSUE THREAD

**Issue by flyoffacliff** [georgezhao2010/midea_ac_lan#146]
What does "customize" do in the "extra entities" menu? I can't find any documentation on how to use this.

Is there a way to set prompt tone to false permanently and not have it revert back when restarting?

**Comment by BenJewell** [comment]
I ended up just modifying the template value in the Python code to disable the sounds.

I still find home assistant very difficult to use though.

**Comment by cash18** [comment]
I'm just fighting with this component. I added an heat pump and i have the complete control of it through HA, without any problems. Right now it's missing the functionality of "Eco_mode" that for me it's important.
![image](https://user-images.githubusercontent.com/20306260/205628714-6707fa5e-81e6-4fb6-b47b-9d43b36bd15d.png)
I just tried to adding from the customize section from the configuration of the device, but i don't know to figure it out.

**Comment by Perfect-Web** [comment]
same here, can we please get some guidance?

**Comment by IGaMbLeRI** [comment]
Also interested in this. Currently whatever value I set, e.g. `{'prompt_tone': False}` or `'prompt_tone': False` result in the following showing up in the logs upon Reload of the Integration:

```
2023-04-26 15:01:40.791 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.793 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.795 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 175, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.796 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 201, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.798 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 149, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.798 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 175, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.799 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 121, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.806 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 175, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.808 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 201, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.809 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 149, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.810 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 175, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.810 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 121, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.812 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 89, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.813 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 89, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.814 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 128, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.815 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 128, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.816 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Inventor EP3-WIFI16L | Bedroom for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 118, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-04-26 15:01:40.838 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 131, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.841 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 169, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.842 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 195, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.844 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 143, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.845 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 169, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.847 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 115, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.848 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 83, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.849 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 122, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.855 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 131, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.857 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 169, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.858 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 195, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.859 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 143, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.860 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 169, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.861 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 115, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.863 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 83, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.864 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 122, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:40.865 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Inventor EP3-WIFI16L | Bedroom for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 112, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 169, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2023-04-26 15:01:45.696 DEBUG (EP3-WIFI16L) [custom_components.midea_ac_lan.midea.core.device] [141837000164292] Connected
2023-04-26 15:01:45.697 DEBUG (EP3-WIFI16L) [custom_components.midea_ac_lan.midea.core.device] [141837000164292] Handshaking
2023-04-26 15:01:45.751 DEBUG (EP3-WIFI16L) [custom_components.midea_ac_lan.midea.core.device] [141837000164292] Authentication success
2023-04-26 15:01:45.751 DEBUG (EP3-WIFI16L) [custom_components.midea_ac_lan.midea.core.device] [141837000164292] Sending: {'header': 'aa1da1000000000000a0', 'body': '00000000000000000000000000000000000000', 'message type': 'a0', 'body type': '00'}
2023-04-26 15:01:52.752 DEBUG (EP3-WIFI16L) [custom_components.midea_ac_lan.midea.core.device] [141837000164292] Unknown error AttributeError("'NoneType' object has no attribute 'recv'")
2023-04-26 15:01:55.763 DEBUG (EP3-WIFI16L) [custom_components.midea_ac_lan.midea.core.device] [141837000164292] Sending: {'header': 'aa20a100000000000003', 'body': '418100ff00000000000000000000000000000000304b', 'message type': '03', 'body type': '41'}
2023-04-26 15:01:55.882 DEBUG (EP3-WIFI16L) [custom_components.midea_ac_lan.midea.devices.a1.device] [141837000164292] Received: {'header': 'aa22a100000000000303', 'body': 'c80002507f7f002300400000000000003e640000000030c6', 'message type': '03', 'body type': 'c8'}
2023-04-26 15:01:55.883 DEBUG (EP3-WIFI16L) [custom_components.midea_ac_lan.midea.core.device] [141837000164292] Status update: {'power': False, 'child_lock': False, 'mode': 'Continuous', 'fan_speed': 'High', 'swing': False, 'target_humidity': 35, 'anion': True, 'tank': 0, 'water_level_set': '0', 'current_humidity': 62}
2023-04-26 15:01:55.883 DEBUG (EP3-WIFI16L) [custom_components.midea_ac_lan.midea.core.device] [141837000164292] Status update: {'available': True}
```

At the same time, I can no longer unset the value of the Customize field to nothing - it simply retains the previous value that results in the error.

**Comment by georgezhao2010** [comment]
Not all types of device support Customize, you could found it in document of device.

Customize for air-conditioner https://github.com/georgezhao2010/midea_ac_lan/blob/master/doc/AC.md#customize
