### ISSUE TITLE
美的电热水器不能设置目标问题

### ISSUE THREAD

**Issue by SLboat** [georgezhao2010/midea_ac_lan#164]
电热水器可以添加，可以控制，但是不能设置目标温度，日志里一直提示这个出错

```txt
Logger: homeassistant
Source: custom_components/midea_ac_lan/water_heater.py:55
Integration: Midea AC LAN ([documentation](https://github.com/georgezhao2010/midea_ac_lan), [issues](https://github.com/georgezhao2010/midea_ac_lan/issues))
First occurred: 14:07:19 (24 occurrences)
Last logged: 14:14:39

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 535, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 180, in capability_attributes
    supported_features = self.supported_features or 0
  File "/config/custom_components/midea_ac_lan/water_heater.py", line 55, in supported_features
    return WaterHeaterEntityFeature.TARGET_TEMPERATURE
NameError: name 'WaterHeaterEntityFeature' is not defined
```

**Comment by SLboat** [comment]
是我的HA版本太老了，更新后OK了！感谢作者的辛苦劳动
