### ISSUE TITLE
508冰箱无法添加

### ISSUE THREAD

**Issue by mysteryfuko** [georgezhao2010/midea_ac_lan#253]
2023-08-04 14:12:54.548 DEBUG (Refrigerator) [custom_components.midea_ac_lan.midea.core.device] [210006723951559] Sending: {'header': 'aa0bca00000000000003', 'body': '00', 'message type': '03', 'body type': '00'}
2023-08-04 14:12:54.781 DEBUG (Refrigerator) [custom_components.midea_ac_lan.midea.devices.ca.device] [210006723951559] Received: {'header': 'aa2dcae7000000000003', 'body': '00006513130500000000000000000000006e3d286e00000000006e1500000000000000', 'message type': '03', 'body type': '00'}
2023-08-04 14:12:54.781 DEBUG (Refrigerator) [custom_components.midea_ac_lan.midea.core.device] [210006723951559] Status update: {'energy_consumption': 0, 'refrigerator_actual_temp': 5.0, 'freezer_actual_temp': -19.5, 'flex_zone_actual_temp': -30.0, 'right_flex_zone_actual_temp': 5.0, 'refrigerator_setting_temp': 5, 'freezer_setting_temp': -18, 'flex_zone_setting_temp': 0, 'right_flex_zone_setting_temp': 0}
2023-08-04 14:12:57.760 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.discover] Received broadcast from ('192.168.31.182', 6445): 837000c8200f00005a5a0111b8007a8000000000ed5b0c0e04081714c77b2e0000bf00000000000000000180000000002b5b3f9d6aa9ebbe10850a0c5ae4e0e58882012f3ee7af87ab7562de98f4f737c0990f62544993828abe527393c0eb90230e3810959a0e8d1eabd0019b8966a23a467b9f1326940e3e63706cd4e06a73b64bd92ec8351ec72c46c4270cc7736c4bdfb3e16e33d88768cc4c3d0658937d96fbcce99f70c976413c2f05f60f82e7ca64616bdbc6c877dc2314bc835bba7919583b0afdc5db0da7e38a0f5ccf4b6a
2023-08-04 14:12:57.761 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.discover] Declassified reply: b61fa8c02c19000030303030434135313133313041303830383335323631313730353331374456340d6d696465615f63615f303533310000bf0102000000000000000000ca00380000000000fcdf00443369059007042306010301000000000000000000000000000000000000000000000000000000000000000000
2023-08-04 14:12:57.761 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.discover] Found a supported device: {'device_id': 210006723951559, 'type': 202, 'ip_address': '192.168.31.182', 'port': 6444, 'model': '310A0808', 'sn': '_________________________________________', 'protocol': 3}
2023-08-04 14:12:57.766 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.discover] Received broadcast from ('192.168.31.182', 6445): 837000c8200f00005a5a0111b8007a8000000000ed5b0c0e04081714c77b2e0000bf00000000000000000180000000002b5b3f9d6aa9ebbe10850a0c5ae4e0e58882012f3ee7af87ab7562de98f4f737c0990f62544993828abe527393c0eb90230e3810959a0e8d1eabd0019b8966a23a467b9f1326940e3e63706cd4e06a73b64bd92ec8351ec72c46c4270cc7736c4bdfb3e16e33d88768cc4c3d0658937d96fbcce99f70c976413c2f05f60f82e7ca64616bdbc6c877dc2314bc835bba7919583b0afdc5db0da7e38a0f5ccf4b6a
2023-08-04 14:12:57.853 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.discover] Received broadcast from ('192.168.31.182', 6445): 837000c8200f00005a5a0111b8007a8000000000ed5b0c0e04081714c77b2e0000bf00000000000000000180000000002b5b3f9d6aa9ebbe10850a0c5ae4e0e58882012f3ee7af87ab7562de98f4f737c0990f62544993828abe527393c0eb90230e3810959a0e8d1eabd0019b8966a23a467b9f1326940e3e63706cd4e06a73b64bd92ec8351ec72c46c4270cc7736c4bdfb3e16e33d88768cc4c3d0658937d96fbcce99f70c976413c2f05f60f82e7ca64616bdbc6c877dc2314bc835bba7919583b0afdc5db0da7e38a0f5ccf4b6a
2023-08-04 14:13:04.315 DEBUG (Dishwasher) [custom_components.midea_ac_lan.midea.devices.e1.device] [210006723805557] Received: {'header': 'aa2de1cc0000c3000004', 'body': '00000000002100000000001c00020000001800000000000003000000000000000000f0', 'message type': '04', 'body type': '00'}
2023-08-04 14:13:04.315 DEBUG (Dishwasher) [custom_components.midea_ac_lan.midea.core.device] [210006723805557] Status update: {'power': False, 'status': 'Off', 'mode': 0, 'additional': 0, 'uv': False, 'dry': False, 'dry_status': False, 'door': False, 'rinse_aid': False, 'salt': False, 'child_lock': False, 'storage': True, 'storage_status': False, 'time_remaining': 0, 'progress': 'Idle', 'storage_remaining': 0, 'temperature': 28, 'humidity': 0}
2023-08-04 14:13:09.180 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 581, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'strong'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 879, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 577, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
    raise ValueError(

**Comment by georgezhao2010** [comment]
日志显示你的冰箱已经添加成功了并且正常返回信息了，210006723951559就是你添加的冰箱设备对吧

**Comment by mysteryfuko** [comment]
并没有这个设备
![image](https://github.com/georgezhao2010/midea_ac_lan/assets/6713863/3f21f619-3f7b-4b96-b2f4-55f4e72875b4)

**Comment by mysteryfuko** [comment]
嗷嗷。发现了。。没有实体。我以为没添加成功

**Comment by georgezhao2010** [comment]
> 嗷嗷。发现了。。没有实体。我以为没添加成功

实体需要要你自己在选项中自己配置，请看说明文档
