### ISSUE TITLE
无法加载配置向导: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by JonathanKang** [georgezhao2010/midea_ac_lan#319]
### HA版本

2023.9.1

### 集成版本

0.3.21

### 设备类型及型号

无

### 使用的App

美的美居

### 问题详细描述

登陆美的美居账号后，点击选项就会出现截图中的错误。具体日志如下。
![Screenshot from 2023-09-21 09-48-31](https://github.com/georgezhao2010/midea_ac_lan/assets/5607743/51369deb-d704-4690-9c16-5e35fb28378a)

### The logs

```
Logger: aiohttp.server
Source: custom_components/midea_ac_lan/config_flow.py:367
Integration: Midea AC LAN ([documentation](https://github.com/georgezhao2010/midea_ac_lan#readme), [issues](https://github.com/georgezhao2010/midea_ac_lan/issues))
First occurred: 09:40:59 (8 occurrences)
Last logged: 09:51:10
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 213, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 270, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/config_flow.py", line 367, in async_step_init
    for attribute, attribute_config in MIDEA_DEVICES.get(self._device_type).get("entities").items():
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by georgezhao2010** [comment]
知道了，那你就不要点选项好了，账号这个配置也没有选项可以配置，回头我会屏蔽掉。

> ### HA版本
> 2023.9.1
> 
> ### 集成版本
> 0.3.21
> 
> ### 设备类型及型号
> 无
> 
> ### 使用的App
> 美的美居
> 
> ### 问题详细描述
> 登陆美的美居账号后，点击选项就会出现截图中的错误。具体日志如下。

知道了，那你就不要点选项好了，账号这个配置也没有选项可以配置，回头我会屏蔽掉。

**Comment by JonathanKang** [comment]
> 
> 知道了，那你就不要点选项好了，账号这个配置也没有选项可以配置，回头我会屏蔽掉。

我的账号下面有两个设备，一个洗衣机和一个冰箱。这意味着这两个设备都没法通过Midea AC LAN来添加到HA吗？

**Comment by JonathanKang** [comment]
原来是要点击`添加设备`。已经搞定了，谢谢。
