### ISSUE TITLE
嵌入式消毒柜集成后没有任何实体

### ISSUE THREAD

**Issue by Plaudern** [georgezhao2010/midea_ac_lan#323]
### HA版本

2023.9.2

### 集成版本

0.3.21

### 设备类型及型号

161628212260633 (Dish Sterilizer)

### 使用的App

美的家具

### 问题详细描述

感谢大佬在昨日的新版本中添加了消毒柜的支持。
![屏幕截图 2023-09-22 060431](https://github.com/georgezhao2010/midea_ac_lan/assets/40253092/5946b01b-6ef6-48fd-8c99-117ba57c7872)
这是自动添加时默认的参数，添加后设备没有任何实体，不可操作
![屏幕截图 2023-09-22 060724](https://github.com/georgezhao2010/midea_ac_lan/assets/40253092/68fdab20-b716-45bd-a9ab-df5f4ad526fd)

### The logs

```
2023-09-21 19:52:22.995 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-21 19:52:22.996 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration midea_ac_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-21 19:52:22.996 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-21 19:52:22.997 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-21 19:52:31.961 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform hassio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 211, in add_to_platform_start
    self._async_read_entity_options()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 785, in _async_read_entity_options
    registry.async_update_entity_options(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1025, in async_update_entity_options
    old = self.entities[entity_id]
          ~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/local/lib/python3.11/collections/__init__.py", line 1126, in __getitem__
    raise KeyError(key)
KeyError: None
2023-09-21 19:52:31.965 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up hassio platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 211, in add_to_platform_start
    self._async_read_entity_options()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 785, in _async_read_entity_options
    registry.async_update_entity_options(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1025, in async_update_entity_options
    old = self.entities[entity_id]
          ~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/local/lib/python3.11/collections/__init__.py", line 1126, in __getitem__
    raise KeyError(key)
KeyError: None
2023-09-21 19:52:33.026 WARNING (MainThread) [homeassistant.components.workday] No holiday found matching datetime.date(2023, 10, 7)
2023-09-21 19:52:33.029 WARNING (MainThread) [homeassistant.components.workday] No holiday found matching datetime.date(2023, 10, 8)
2023-09-21 19:52:35.320 ERROR (MainThread) [homeassistant.components.homekit] HomeKit Plaudern  Play Control cannot startup: entity not available: {'include_domains': [], 'exclude_domains': [], 'include_entities': ['media_player.xiaomi_rmi1_6edd_play_control'], 'exclude_entities': [], 'exclude_entity_globs': [], 'include_entity_globs': []}
2023-09-21 20:01:26.165 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 213, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 270, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/config_flow.py", line 367, in async_step_init
    for attribute, attribute_config in MIDEA_DEVICES.get(self._device_type).get("entities").items():
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2023-09-21 22:03:52.213 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Bad status line "Invalid method encountered:\n\n  b'MGLNDD_27.227.184.99_8123'\n     ^"
2023-09-22 03:28:45.525 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.xiaomi_c16_9d00_air_conditioner is taking over 10 seconds
2023-09-22 03:28:45.982 ERROR (MainThread) [custom_components.xiaomi_miot.climate] 米家空调(睡眠版)(xiaomi.aircondition.c16): Got MiioException while fetching the state: Unable to discover the device 192.168.8.203, mapping: {'air_conditioner.on': {'siid': 2, 'piid': 1}, 'air_conditioner.mode': {'siid': 2, 'piid': 2}, 'air_conditioner.fault': {'siid': 2, 'piid': 3}, 'target_temperature-2-4': {'siid': 2, 'piid': 4}, 'air_conditioner.eco': {'siid': 2, 'piid': 7}, 'air_conditioner.heater': {'siid': 2, 'piid': 9}, 'air_conditioner.dryer': {'siid': 2, 'piid': 10}, 'air_conditioner.sleep_mode': {'siid': 2, 'piid': 11}, 'air_conditioner.target_humidity': {'siid': 2, 'piid': 14}, 'unstraight_blowing-2-15': {'siid': 2, 'piid': 15}, 'fault_value': {'siid': 13, 'piid': 1}, 'machine_state.indoor_pipe_temp': {'siid': 12, 'piid': 1}, 'machine_state.indoor_fan_speed': {'siid': 12, 'piid': 3}, 'real_heater_switch-12-4': {'siid': 12, 'piid': 4}, 'realindoor_fan_lever-12-5': {'siid': 12, 'piid': 5}, 'machine_state.outdoor_temp': {'siid': 12, 'piid': 7}, 'machine_state.outdoor_pipe_temp': {'siid': 12, 'piid': 8}, 'outdoor_exhaust_temp-12-9': {'siid': 12, 'piid': 9}, 'machine_state.outdoor_fan_lever': {'siid': 12, 'piid': 10}, 'compressor_frequency-12-11': {'siid': 12, 'piid': 11}, 'fourway_valve_switch-12-12': {'siid': 12, 'piid': 12}, 'machine_state.outdoor_current': {'siid': 12, 'piid': 13}, 'machine_state.outdoor_m_voltage': {'siid': 12, 'piid': 14}, 'machine_state.expansion_valve': {'siid': 12, 'piid': 15}, 'longitude_latitude-12-16': {'siid': 12, 'piid': 16}, 'machine_state.ambient_light': {'siid': 12, 'piid': 19}, 'iot_linkage.iot_temp': {'siid': 11, 'piid': 1}, 'iot_linkage.temp_ctrl': {'siid': 11, 'piid': 5}, 'iot_linkage.smart_sleep_ctrl': {'siid': 11, 'piid': 6}, 'enhance.fan_percent': {'siid': 10, 'piid': 1}, 'enhance.timer': {'siid': 10, 'piid': 3}, 'enhance.humidity_range': {'siid': 10, 'piid': 6}, 'enhance.temperature_humidity': {'siid': 10, 'piid': 9}, 'maintenance.clean': {'siid': 9, 'piid': 1}, 'maintenance.examine': {'siid': 9, 'piid': 2}, 'maintenance.running_duration': {'siid': 9, 'piid': 5}, 'electricity': {'siid': 8, 'piid': 1}, 'electricity.elec_count': {'siid': 8, 'piid': 3}, 'indicator_light.on': {'siid': 6, 'piid': 1}, 'indicator_light.brightness': {'siid': 6, 'piid': 2}, 'alarm': {'siid': 5, 'piid': 1}, 'environment.temperature': {'siid': 4, 'piid': 7}, 'environment.relative_humidity': {'siid': 4, 'piid': 9}, 'fan_control.fan_level': {'siid': 3, 'piid': 2}, 'fan_control.vertical_swing': {'siid': 3, 'piid': 4}}, max_properties: 9/45
2023-09-22 05:59:10.555 WARNING (SyncWorker_11) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-22 05:59:10.556 WARNING (SyncWorker_11) [homeassistant.loader] We found a custom integration midea_ac_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-22 05:59:10.557 WARNING (SyncWorker_11) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-22 05:59:10.557 WARNING (SyncWorker_11) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-22 06:01:49.681 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 213, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 270, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/config_flow.py", line 367, in async_step_init
    for attribute, attribute_config in MIDEA_DEVICES.get(self._device_type).get("entities").items():
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by georgezhao2010** [comment]
> ### 问题详细描述
> 感谢大佬在昨日的新版本中添加了消毒柜的支持。 

你读过README吗？知道实体如何生成吗？什么感谢不感谢的，写了上万字README你们看都不看一眼。

在你消毒柜上点选项看看呢？

**Comment by georgezhao2010** [comment]
没有更多回应该issue暂时关闭，如果有进一步信息再打开

**Comment by Plaudern** [comment]
> > ### 问题详细描述
> > 感谢大佬在昨日的新版本中添加了消毒柜的支持。
> 
> 你读过README吗？知道实体如何生成吗？什么感谢不感谢的，写了上万字README你们看都不看一眼。
> 
> 在你消毒柜上点选项看看呢？

![屏幕截图 2023-10-01 021610](https://github.com/georgezhao2010/midea_ac_lan/assets/40253092/d62043cc-28fc-4a7f-a0c5-abff7ed060f5)
如果说的是这里的话我都勾选了

**Comment by georgezhao2010** [comment]
> > > ### 问题详细描述
> > > 感谢大佬在昨日的新版本中添加了消毒柜的支持。
> > 
> > 
> > 你读过README吗？知道实体如何生成吗？什么感谢不感谢的，写了上万字README你们看都不看一眼。
> > 在你消毒柜上点选项看看呢？
> 
> 如果说的是这里的话我都勾选了

 所以呢？这不是有18个实体吗？

![image](https://github.com/georgezhao2010/midea_ac_lan/assets/27534713/dbf5e0b4-da78-472d-b9f3-abf662984867)

要么你就提供一下类似以下内容的日志
```
2023-10-01 08:36:24.448 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Connected
2023-10-01 08:36:24.448 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Handshaking
2023-10-01 08:36:24.911 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Authentication success
2023-10-01 08:36:24.911 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Sending: {'header': 'aa1db3000000000000a0', 'body': '00000000000000000000000000000000000000', 'message type': 'a0', 'body type': 'None'}
2023-10-01 08:36:34.918 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Does not supports the protocol MessageQueryAppliance, ignored
2023-10-01 08:36:34.919 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Sending: {'header': 'aa0bb300000000000003', 'body': '31', 'message type': '03', 'body type': '31'}
2023-10-01 08:36:44.927 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Does not supports the protocol MessageQuery, ignored
2023-10-01 08:36:44.927 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Refresh status is timed out
2023-10-01 08:36:44.927 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Status update: {'available': False}
2023-10-01 08:36:49.928 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Connecting to 192.168.1.132:6444
2023-10-01 08:36:49.930 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Connected
2023-10-01 08:36:49.930 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Handshaking
2023-10-01 08:36:50.456 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Authentication success
2023-10-01 08:36:50.456 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Sending: {'header': 'aa1db3000000000000a0', 'body': '00000000000000000000000000000000000000', 'message type': 'a0', 'body type': 'None'}
2023-10-01 08:37:00.464 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Does not supports the protocol MessageQueryAppliance, ignored
2023-10-01 08:37:00.464 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Sending: {'header': 'aa0bb300000000000003', 'body': '31', 'message type': '03', 'body type': '31'}
2023-10-01 08:37:10.468 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Does not supports the protocol MessageQuery, ignored
2023-10-01 08:37:10.468 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Refresh status is timed out
2023-10-01 08:37:10.468 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Status update: {'available': False}
2023-10-01 08:37:15.470 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Connecting to 192.168.1.132:6444
2023-10-01 08:37:15.472 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Connected
2023-10-01 08:37:15.472 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Handshaking
2023-10-01 08:37:15.977 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Authentication success
2023-10-01 08:37:15.977 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Sending: {'header': 'aa1db3000000000000a0', 'body': '00000000000000000000000000000000000000', 'message type': 'a0', 'body type': 'None'}
2023-10-01 08:37:25.984 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Does not supports the protocol MessageQueryAppliance, ignored
2023-10-01 08:37:25.984 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Sending: {'header': 'aa0bb300000000000003', 'body': '31', 'message type': '03', 'body type': '31'}
2023-10-01 08:37:35.987 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Does not supports the protocol MessageQuery, ignored
2023-10-01 08:37:35.987 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Refresh status is timed out
2023-10-01 08:37:35.987 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Status update: {'available': False}
2023-10-01 08:37:40.989 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Connecting to 192.168.1.132:6444
2023-10-01 08:37:40.991 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Connected
2023-10-01 08:37:40.991 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Handshaking
2023-10-01 08:37:41.452 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Authentication success
2023-10-01 08:37:41.452 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Sending: {'header': 'aa1db3000000000000a0', 'body': '00000000000000000000000000000000000000', 'message type': 'a0', 'body type': 'None'}
2023-10-01 08:37:51.455 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Does not supports the protocol MessageQueryAppliance, ignored
2023-10-01 08:37:51.455 DEBUG (消毒碗柜) [custom_components.midea_ac_lan.midea.core.device] [1627XXXXXXXXX1] Sending: {'header': 'aa0bb300000000000003', 'body': '31', 'message type': '03', 'body type': '31'}
```

**Comment by georgezhao2010** [comment]
> 日志是我删除设备（美的和ha里都删除重置联网后），重新添加的所以ip变了

我看的日志中你的设备访问正常，你自己点设备旁边的选项，把需要的设备勾选出来就行了。

**Comment by Plaudern** [comment]
> > 日志是我删除设备（美的和ha里都删除重置联网后），重新添加的所以ip变了
> 
> 我看的日志中你的设备访问正常，你自己点设备旁边的选项，把需要的设备勾选出来就行了。
> 
> 难道这样做完了没有实体出现？

我勾选了所有选项，并没有实体出现

**Comment by Plaudern** [comment]
已经是最新版本，日志里都能看见上下层的温度，各种重新添加，重启依旧是没有实体

> Home Assistant 2023.10.1
>
> Supervisor 2023.10.0
>
> Operating System 10.5
>
> 前端版本： 20231005.0 - latest

大佬方便的话可以帮我远程看一下么，ha有外网访问

**Comment by dasiniwoyebushuo** [comment]
确实没有 我也没有 不知道什么原因
