### ISSUE TITLE
Error on start rendering integration unavailable

### ISSUE THREAD

**Issue by rcmurphy** [georgezhao2010/midea_ac_lan#34]
This error happens even after a clean reboot. I never encountered it prior to the most recent release.

```This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/midea_ac_lan/midea/core/device.py:122 
Integration: Midea AC LAN (documentation, issues) 
First occurred: 19:15:29 (1 occurrences) 
Last logged: 19:15:29

Error executing service: <ServiceCall climate.set_temperature (c:01G963WJ6VJ18317SQASY7TBXF): hvac_mode=cool, temperature=23.5, entity_id=['climate.owners_suite_hvac']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1731, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 588, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 446, in async_set_temperature
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/midea_ac_lan/climate.py", line 127, in set_temperature
    self._device.set_target_temperature(
  File "/config/custom_components/midea_ac_lan/midea/devices/ac/device.py", line 162, in set_target_temperature
    self.build_send(message)
  File "/config/custom_components/midea_ac_lan/midea/core/device.py", line 132, in build_send
    self.send_message(msg)
  File "/config/custom_components/midea_ac_lan/midea/core/device.py", line 118, in send_message
    self.send_message_V2(data)
  File "/config/custom_components/midea_ac_lan/midea/core/device.py", line 122, in send_message_V2
    self._socket.send(data)
OSError: [Errno 9] Bad file descriptor
```

**Comment by rcmurphy** [comment]
I think this is actually caused whenever the AC is off-line, however, the entities seem to be represented differently than when, for example, A Z wave device goes off-line
