### ISSUE TITLE
Integration non load

### ISSUE THREAD

**Issue by AgatGit** [georgezhao2010/midea_ac_lan#356]
### HA core version

2022.11.1

### Intergration version

0.3.22

### Device type and model

Dishwasher E1

### Used App

MSmartHome

### The description of problem

Try add midea_ac_lan integration, and HA say  Error Config flow could not be loaded: {"message":"Invalid handler specified"}

HA log

2023-10-18 13:13:34.952 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.midea_ac_lan.config_flow
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/midea_ac_lan/config_flow.py", line 39, in <module>
    from .midea.core.cloud import get_midea_cloud
  File "/home/homeassistant/.homeassistant/custom_components/midea_ac_lan/midea/core/cloud.py", line 54, in <module>
    class MideaCloud:
  File "/home/homeassistant/.homeassistant/custom_components/midea_ac_lan/midea/core/cloud.py", line 81, in MideaCloud
    async def _api_request(self, endpoint: str, data: dict, header=None) -> dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
2023-10-18 13:13:34.961 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration midea_ac_lan: Exception importing custom_components.midea_ac_lan.config_flow

**Comment by josephworks** [comment]
I am having the same issue.
