### ISSUE TITLE
Controls broke after laters update

### ISSUE THREAD

**Issue by Buniculbroscoi** [georgezhao2010/midea_ac_lan#553]
### HA core version

2024.6.4

### Intergration version

v0.4.2

### Device type and model

Inventor Omnia eco

### Used App

Msmarthome

### The description of problem

Latest update broke all the controls of the AC from HA UI as well as homekit. Every action results in the error BrokenPipeError: [Errno 32] Broken pipe

Earlier today, before the update, everything was working flawlessly.

### The logs

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 738, in async_handle_set_fan_mode_service
    await self.async_set_fan_mode(fan_mode)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 746, in async_set_fan_mode
    await self.hass.async_add_executor_job(self.set_fan_mode, fan_mode)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/climate.py", line 300, in set_fan_mode
    self._device.set_attribute(attr=ACAttributes.fan_speed, value=fan_speed)
  File "/usr/local/lib/python3.12/site-packages/midealocal/devices/ac/__init__.py", line 365, in set_attribute
    self.build_send(message)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 283, in build_send
    self.send_message(msg)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 254, in send_message
    self.send_message_v3(data, msg_type=MSGTYPE_ENCRYPTED_REQUEST)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 276, in send_message_v3
    self.send_message_v2(data)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 261, in send_message_v2
    self._socket.send(data)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by rokam** [comment]
https://github.com/wuwentao/midea_ac_lan/
