### ISSUE TITLE
Since 0.5.0 and 0.5.1 it stopped working 

### ISSUE THREAD

**Issue by sanderlv** [georgezhao2010/midea_ac_lan#560]
Error:

Logger: midealocal.device
Source: /usr/local/lib/python3.12/site-packages/midealocal/device.py:239
First occurred: 18:26:29 (1 occurrences)
Last logged: 18:26:29

[146235046613512] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 219
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 219, in connect
    self.refresh_status(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 344, in refresh_status
    raise SocketException
midealocal.exceptions.SocketException

**Comment by wuwentao** [comment]
you may using new version from : https://github.com/wuwentao/midea_ac_lan
please try with latest version, if bug still exist, please follow the issue template and report your bug
