### ISSUE TITLE
Integration using deprecated terms

### ISSUE THREAD

**Issue by T-Fyre** [georgezhao2010/midea_ac_lan#607]
### HA版本

2024.9.1

### 集成版本

3.22

### 设备类型及型号

All?

### 使用的App

SmartHome

### 问题详细描述

The integration is currently using extremely outdated terms in its code, support for a buncha these deprecated lines is set to be discontinued in 2025.1 and will likely render most if not all of the code broken and unusable

### The logs

2024-11-12 05:21:01.590 WARNING (ImportExecutor_0) [homeassistant.const] TIME_DAYS was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.DAYS instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:01.598 WARNING (ImportExecutor_0) [homeassistant.const] TIME_HOURS was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.HOURS instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:01.605 WARNING (ImportExecutor_0) [homeassistant.const] TIME_MINUTES was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:01.612 WARNING (ImportExecutor_0) [homeassistant.const] TIME_SECONDS was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.SECONDS instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:01.620 WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:01.626 WARNING (ImportExecutor_0) [homeassistant.const] POWER_WATT was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:01.633 WARNING (ImportExecutor_0) [homeassistant.const] VOLUME_LITERS was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfVolume.LITERS instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:01.640 WARNING (ImportExecutor_0) [homeassistant.const] ENERGY_KILO_WATT_HOUR was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:02.290 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('.ac.device', 'custom_components.midea_ac_lan.midea.devices') inside the event loop by custom integration 'midea_ac_lan' at custom_components/midea_ac_lan/midea/devices/__init__.py, line 23: module = import_module(device_path, __package__) (offender: /config/custom_components/midea_ac_lan/midea/devices/__init__.py, line 23: module = import_module(device_path, __package__)), please create a bug report at https://github.com/georgezhao2010/midea_ac_lan/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/midea_ac_lan/__init__.py", line 148, in async_setup_entry
    device = device_selector(
  File "/config/custom_components/midea_ac_lan/midea/devices/__init__.py", line 23, in device_selector
    module = import_module(device_path, __package__)

2024-11-12 05:21:02.307 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'midea_ac_lan' calls async_forward_entry_setup for integration, midea_ac_lan with title: Bedroom AC and entry_id: 0cca71dfc7f8c5757d02aff3428201fc, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/midea_ac_lan/__init__.py, line 171: hass.async_create_task(hass.config_entries.async_forward_entry_setup(, please create a bug report at https://github.com/georgezhao2010/midea_ac_lan/issues
2024-11-12 05:21:14.367 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration midea_ac_lan with title: Bedroom AC and entry_id: 0cca71dfc7f8c5757d02aff3428201fc, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2184, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1201, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
    _LOGGER.warning(msg, stack_info=True)
2024-11-12 05:21:14.375 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration midea_ac_lan with title: Kitchen AC and entry_id: 50ea8bfd89473ab31a3b524de9baf1f3, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2184, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1201, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
    _LOGGER.warning(msg, stack_info=True)
2024-11-12 05:21:14.384 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration midea_ac_lan with title: Bedroom AC and entry_id: 0cca71dfc7f8c5757d02aff3428201fc, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2184, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1201, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
    _LOGGER.warning(msg, stack_info=True)
2024-11-12 05:21:14.381 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_AUTO was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.AUTO instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.394 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_COOL was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.398 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration midea_ac_lan with title: Kitchen AC and entry_id: 50ea8bfd89473ab31a3b524de9baf1f3, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2184, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1201, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
    _LOGGER.warning(msg, stack_info=True)
2024-11-12 05:21:14.406 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_DRY was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.DRY instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.415 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_FAN_ONLY was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.FAN_ONLY instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.424 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_HEAT was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.431 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_HEAT_COOL was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT_COOL instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.440 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_OFF was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.448 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_AUX_HEAT was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.AUX_HEAT instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.457 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_FAN_MODE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.465 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_PRESET_MODE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.473 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_SWING_MODE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.481 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_TARGET_HUMIDITY was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_HUMIDITY instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.490 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_TARGET_TEMPERATURE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.498 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_TARGET_TEMPERATURE_RANGE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE_RANGE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.506 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_AUTO was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.AUTO instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.514 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_COOL was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.522 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_DRY was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.DRY instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.530 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_FAN_ONLY was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.FAN_ONLY instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.538 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_HEAT was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.547 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_HEAT_COOL was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT_COOL instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.554 WARNING (ImportExecutor_0) [homeassistant.components.climate] HVAC_MODE_OFF was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.563 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_AUX_HEAT was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.AUX_HEAT instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.571 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_FAN_MODE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.579 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_PRESET_MODE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.587 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_SWING_MODE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.595 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_TARGET_HUMIDITY was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_HUMIDITY instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.603 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_TARGET_TEMPERATURE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.611 WARNING (ImportExecutor_0) [homeassistant.components.climate] SUPPORT_TARGET_TEMPERATURE_RANGE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE_RANGE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.620 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_OFF was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.628 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_HEAT was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.636 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_COOL was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.645 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_HEAT_COOL was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT_COOL instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.652 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_AUTO was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.AUTO instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.661 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_DRY was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.DRY instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.669 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_FAN_ONLY was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.FAN_ONLY instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.676 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] CURRENT_HVAC_OFF was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.OFF instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.685 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] CURRENT_HVAC_HEAT was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.HEATING instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.693 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] CURRENT_HVAC_COOL was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.COOLING instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.701 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] CURRENT_HVAC_DRY was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.DRYING instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.709 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] CURRENT_HVAC_IDLE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.IDLE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.717 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] CURRENT_HVAC_FAN was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.FAN instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.725 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.734 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE_RANGE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE_RANGE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.742 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_TARGET_HUMIDITY was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_HUMIDITY instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.750 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_FAN_MODE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.758 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_PRESET_MODE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.766 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_SWING_MODE was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.775 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_AUX_HEAT was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.AUX_HEAT instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.783 WARNING (ImportExecutor_0) [homeassistant.const] TEMP_CELSIUS was used from midea_ac_lan, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'midea_ac_lan' custom integration
2024-11-12 05:21:14.786 WARNING (MainThread) [homeassistant.components.climate] Entity midea_ac_lan.30786325646678_climate (<class 'custom_components.midea_ac_lan.climate.MideaACClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/georgezhao2010/midea_ac_lan/issues
2024-11-12 05:21:14.787 WARNING (MainThread) [homeassistant.components.climate] Entity midea_ac_lan.30786325646678_climate (<class 'custom_components.midea_ac_lan.climate.MideaACClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/georgezhao2010/midea_ac_lan/issues
2024-11-12 05:21:14.787 WARNING (MainThread) [homeassistant.components.climate] Entity midea_ac_lan.30786325646678_climate (<class 'custom_components.midea_ac_lan.climate.MideaACClimate'>) implements HVACMode(s): off, auto, cool, dry, heat, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/georgezhao2010/midea_ac_lan/issues
2024-11-12 05:21:14.788 WARNING (MainThread) [homeassistant.components.climate] midea_ac_lan::MideaACClimate implements the `is_aux_heat` property or uses the auxiliary  heater methods in a subclass of ClimateEntity which is deprecated and will be unsupported from Home Assistant 2024.10. Please create a bug report at https://github.com/georgezhao2010/midea_ac_lan/issues
2024-11-12 05:21:14.791 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration midea_ac_lan with title: Bedroom AC and entry_id: 0cca71dfc7f8c5757d02aff3428201fc, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2184, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1201, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
    _LOGGER.warning(msg, stack_info=True)
2024-11-12 05:21:14.792 WARNING (MainThread) [homeassistant.components.climate] Entity midea_ac_lan.151732605242358_climate (<class 'custom_components.midea_ac_lan.climate.MideaACClimate'>) does not set

**Comment by rafkra** [comment]
Will not be fixed, check issue #595
