### ISSUE TITLE
Error occurred loading flow for integration midea_ac_lan: cannot import name 'TIME_DAYS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

### ISSUE THREAD

**Issue by mackowskim** [georgezhao2010/midea_ac_lan#629]
### HA core version

2025.1.0b1

### Intergration version

0.3.22

### Device type and model

Air Conditioner Rotenso Versu Cloth

### Used App

NetHome Plus

### The description of problem

**Integration does not load on the latest HOme Assistant Core beta with this error:**

`Error occurred loading flow for integration midea_ac_lan: cannot import name 'TIME_DAYS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`

### The logs

**Additional warning:**

`Detected blocking call to import_module with args ('custom_components.midea_ac_lan.config_flow',) inside the event loop by integration 'config' at homeassistant/components/config/config_entries.py, line 179: return await super()._post_impl(request, data) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1304: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+config%22 For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle return await handler(request) File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post return await self._post_impl(request, data) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl return await super()._post_impl(request, data)`

**Comment by aric89** [comment]
I'm getting this issue as well.

**Comment by ehbush** [comment]
Same.

**Comment by ehbush** [comment]
@georgezhao2010 Let us know if you need any additional information here.

**Comment by rafkra** [comment]
Read issue #595

**Comment by mackowskim** [comment]
Thanks @rafkra I can confirm https://github.com/wuwentao/midea_ac_lan repo is maintained and working fine.
All the best @georgezhao2010! I hope You're doing fine.

**Comment by pauloon** [comment]
Same

**Comment by Alex-11976** [comment]
I also had this issue, but initially, it worked perfectly. Then I made a backup because I had to reinstall Home Assistant. After restoring the backup, the device became unavailable, so I uninstalled the midea_ac_lan integration. When I tried to reinstall it, I encountered the same error.

**Comment by andrasdenk** [comment]
Same

**Comment by erikgieseler** [comment]
This reporistory is dead because the maintainer has not been available for a long time and no more pull requests are being merged. You should switch to https://github.com/wuwentao/midea_ac_lan.
