### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by diedvdyk** [georgezhao2010/midea_ac_lan#74]
Logger: homeassistant.components.climate
Source: helpers/temperature.py:24
Integration: Climate (documentation, issues)
First occurred: 18:35:14 (4 occurrences)
Last logged: 18:35:14

Error adding entities for domain climate with platform midea_ac_lan
Error while setting up midea_ac_lan platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 270, in state_attributes
    ATTR_CURRENT_TEMPERATURE: show_temp(
  File "/usr/src/homeassistant/homeassistant/helpers/temperature.py", line 24, in display_temp
    raise TypeError(f"Temperature is not a number: {temperature}")
TypeError: Temperature is not a number: N/A

**Comment by georgezhao2010** [comment]
> Logger: homeassistant.components.climate Source: helpers/temperature.py:24 Integration: Climate (documentation, issues) First occurred: 18:35:14 (4 occurrences) Last logged: 18:35:14
> 
> Error adding entities for domain climate with platform midea_ac_lan Error while setting up midea_ac_lan platform for climate Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities await asyncio.gather(*tasks) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity await entity.add_to_platform_finish() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _async_write_ha_state attr.update(self.state_attributes or {}) File "/usr/src/homeassistant/homeassistant/components/climate/**init**.py", line 270, in state_attributes ATTR_CURRENT_TEMPERATURE: show_temp( File "/usr/src/homeassistant/homeassistant/helpers/temperature.py", line 24, in display_temp raise TypeError(f"Temperature is not a number: {temperature}") TypeError: Temperature is not a number: N/A

#69
