### ISSUE TITLE
冰箱无法集成

### ISSUE THREAD

**Issue by loveyu** [georgezhao2010/midea_ac_lan#86]
此错误来自自定义集成。

Logger: homeassistant.config_entries
Source: custom_components/midea_ac_lan/midea/devices/ca/device.py:60
Integration: Midea AC LAN (documentation, issues)
First occurred: 23:17:05 (1 occurrences)
Last logged: 23:17:05

Error setting up entry 冰箱 for midea_ac_lan
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/midea_ac_lan/__init__.py", line 119, in async_setup_entry
    device = device_selector(
  File "/config/custom_components/midea_ac_lan/midea/devices/__init__.py", line 17, in device_selector
    device = module.MideaAppliance(
  File "/config/custom_components/midea_ac_lan/midea/devices/ca/device.py", line 60, in __init__
    DeviceAttributes.left_flex_zone_setting_temp: None,
  File "/usr/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: left_flex_zone_setting_temp

**Comment by jiuyaozhuce** [comment]
出现了一样的问题

**Comment by georgezhao2010** [comment]
我的错，请重新下载v0.3.10

**Comment by dwxiayi** [comment]
2022-09-01 00:17:12 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 冰箱 for midea_ac_lan
File "/opt/hass/hassconf/custom_components/midea_ac_lan/__init__.py", line 119, in async_setup_entry
File "/opt/hass/hassconf/custom_components/midea_ac_lan/midea/devices/__init__.py", line 17, in device_selector
File "/opt/hass/hassconf/custom_components/midea_ac_lan/midea/devices/ca/device.py", line 60, in __init__


刚更新的也保存。hass是2022.7.1

**Comment by georgezhao2010** [comment]
> 2022-09-01 00:17:12 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 冰箱 for midea_ac_lan File "/opt/hass/hassconf/custom_components/midea_ac_lan/**init**.py", line 119, in async_setup_entry File "/opt/hass/hassconf/custom_components/midea_ac_lan/midea/devices/**init**.py", line 17, in device_selector File "/opt/hass/hassconf/custom_components/midea_ac_lan/midea/devices/ca/device.py", line 60, in **init**
> 
> 刚更新的也保存。hass是2022.7.1

你选重新下载

**Comment by dwxiayi** [comment]
可以了
