### ISSUE TITLE
电热水器无法正常工作，日志打印unknow error

### ISSUE THREAD

**Issue by YinHangCode** [georgezhao2010/midea_ac_lan#88]
homeassistant的日志如下：
```
2022-09-02 01:23:16.523 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Connected
2022-09-02 01:23:16.523 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Authentication success
2022-09-02 01:23:16.523 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Sending: {'header': 'aa1de2000000000000a0', 'body': '00000000000000000000000000000000000000', 'message type': 'a0', 'body type': 'None'}
2022-09-02 01:23:18.545 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Unknown error
2022-09-02 01:23:18.546 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Status update: {'available': False}
```

设备信息如下：
```
root@debian:~# midea-discover -cn -i 6.3.17.1 -a 186xxxxxxxx -p Xxxxxxxx -d
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.2.5 Currently only supports ac devices, only support MSmartHome and 美的美居 APP.
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:msmart.scanner:Message sent
DEBUG:msmart.scanner:Midea Local Data 6.3.17.1 5a5a011178007a8000000000000000000000000056fd100000100000000000000000000001000000c0b287546e256f8dcdbe0b45721e3d167314a4396a107ab7cc387ce62617eb42fab666e6fc58fbdb05b4245f85582bd69ec9d97c2c20dd7f5b6a76c34a941b88dcce1fa5b3b4d4d9db3eaa02afb174c0
DEBUG:msmart.scanner:Decrypt Reply: 6.3.17.1 011103062c19000030303030453232313130303033305739533135393138323130313539303030300d6d696465615f65325f30313539
DEBUG:msmart.scanner:*** Found a device: {'name': 'midea_e2_0159', 'ssid': 'midea_e2_0159', 'ip': '6.3.17.1', 'port': 6444, 'id': 17592187157846, 'version': 2, 'token': None, 'key': None, 'type': 'e2', 'sn': '0E221100030W9S159182101590000', 'model': '30W9S', 'support': False, 'run_test': True}
INFO:msmart.cli:*** Found a device: {'name': 'midea_e2_0159', 'ssid': 'midea_e2_0159', 'ip': '6.3.17.1', 'port': 6444, 'id': 17592187157846, 'version': 2, 'token': None, 'key': None, 'type': 'e2', 'sn': '0E221100030W9S159182101590000', 'model': '30W9S', 'support': False, 'run_test': True}
root@debian:~#
```

[e2.lua.zip](https://github.com/georgezhao2010/midea_ac_lan/files/9472032/e2.lua.zip)

**Comment by YinHangCode** [comment]
add logging.exception(e)
```
2022-09-02 01:37:37.806 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Connected
2022-09-02 01:37:37.806 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Authentication success
2022-09-02 01:37:37.806 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Sending: {'header': 'aa1de2000000000000a0', 'body': '00000000000000000000000000000000000000', 'message type': 'a0', 'body type': 'None'}
2022-09-02 01:37:39.753 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Unknown error

2022-09-02 01:37:39.753 ERROR (客卫的热水器) [root] index out of range
Traceback (most recent call last):
  File "/config/custom_components/midea_ac_lan/midea/core/device.py", line 116, in connect
    self.get_sub_type()
  File "/config/custom_components/midea_ac_lan/midea/core/device.py", line 177, in get_sub_type
    result = self.parse_message(msg)
  File "/config/custom_components/midea_ac_lan/midea/core/device.py", line 244, in parse_message
    if self.pre_process_message(decrypted):
  File "/config/custom_components/midea_ac_lan/midea/core/device.py", line 216, in pre_process_message
    message = MessageSubtypeResponse(msg)
  File "/config/custom_components/midea_ac_lan/midea/core/message.py", line 184, in __init__
    self._body = SubtypeMessageBody(body)
  File "/config/custom_components/midea_ac_lan/midea/core/message.py", line 148, in __init__
    self.sub_type = (body[3] << 8) + body[2]
IndexError: index out of range
```

**Comment by georgezhao2010** [comment]
> homeassistant的日志如下：
> 
> ```
> 2022-09-02 01:23:16.523 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Connected
> 2022-09-02 01:23:16.523 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Authentication success
> 2022-09-02 01:23:16.523 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Sending: {'header': 'aa1de2000000000000a0', 'body': '00000000000000000000000000000000000000', 'message type': 'a0', 'body type': 'None'}
> 2022-09-02 01:23:18.545 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Unknown error
> 2022-09-02 01:23:18.546 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Status update: {'available': False}
> ```
> 
> 设备信息如下：
> 
> ```
> root@debian:~# midea-discover -cn -i 6.3.17.1 -a 186xxxxxxxx -p Xxxxxxxx -d
> INFO:msmart.cli:Debug mode active
> INFO:msmart.cli:msmart version: 0.2.5 Currently only supports ac devices, only support MSmartHome and 美的美居 APP.
> DEBUG:asyncio:Using selector: EpollSelector
> DEBUG:msmart.scanner:Message sent
> DEBUG:msmart.scanner:Midea Local Data 6.3.17.1 5a5a011178007a8000000000000000000000000056fd100000100000000000000000000001000000c0b287546e256f8dcdbe0b45721e3d167314a4396a107ab7cc387ce62617eb42fab666e6fc58fbdb05b4245f85582bd69ec9d97c2c20dd7f5b6a76c34a941b88dcce1fa5b3b4d4d9db3eaa02afb174c0
> DEBUG:msmart.scanner:Decrypt Reply: 6.3.17.1 011103062c19000030303030453232313130303033305739533135393138323130313539303030300d6d696465615f65325f30313539
> DEBUG:msmart.scanner:*** Found a device: {'name': 'midea_e2_0159', 'ssid': 'midea_e2_0159', 'ip': '6.3.17.1', 'port': 6444, 'id': 17592187157846, 'version': 2, 'token': None, 'key': None, 'type': 'e2', 'sn': '0E221100030W9S159182101590000', 'model': '30W9S', 'support': False, 'run_test': True}
> INFO:msmart.cli:*** Found a device: {'name': 'midea_e2_0159', 'ssid': 'midea_e2_0159', 'ip': '6.3.17.1', 'port': 6444, 'id': 17592187157846, 'version': 2, 'token': None, 'key': None, 'type': 'e2', 'sn': '0E221100030W9S159182101590000', 'model': '30W9S', 'support': False, 'run_test': True}
> root@debian:~#
> ```
> 
> [e2.lua.zip](https://github.com/georgezhao2010/midea_ac_lan/files/9472032/e2.lua.zip)

这样，你编辑一下mide/core/device.py，删除第130和131行
```
        except Exception:
            _LOGGER.debug(f"[{self._device_id}] Unknown error")
```
然后重启，看打印出的报错日志是什么呢，贴一下

**Comment by YinHangCode** [comment]
![image](https://user-images.githubusercontent.com/15974677/188054431-c40ffdbe-b64c-4853-83d6-e5d8a97ad5aa.png)

输出的内容是
```
aa0de2000000000000a000e2018e
```

**Comment by georgezhao2010** [comment]
> ![image](https://user-images.githubusercontent.com/15974677/188054431-c40ffdbe-b64c-4853-83d6-e5d8a97ad5aa.png)
> 
> 输出的内容是
> 
> ```
> aa0de2000000000000a000e2018e
> ```

你这个机器有意思，除了header和最后一字节校验码以外只有 00 e2 01三个字节，甚至不符合美的自己的协议规定

![image](https://user-images.githubusercontent.com/27534713/188064753-a0b59d7a-7ee7-4137-a1d3-3a5289f8cdf7.png)

我会处理一下然后在下个更新修正

**Comment by YinHangCode** [comment]
这个机器比较老的，之前一直是当非智能的在用，最近才发现这机器有wifi模块才想着折腾一下。
那就辛苦大佬了，有啥能帮得上的地方需要我这边提供啥测试信息啥的随时叫我，感谢。：）

**Comment by georgezhao2010** [comment]
> 这个机器比较老的，之前一直是当非智能的在用，最近才发现这机器有wifi模块才想着折腾一下。 那就辛苦大佬了，有啥能帮得上的地方需要我这边提供啥测试信息啥的随时叫我，感谢。：）

这样，你让`def pre_process_message(self, msg)`这个函数直接返回True，看看是否能配置得起来，功能是否正常。

**Comment by YinHangCode** [comment]
![image](https://user-images.githubusercontent.com/15974677/188104092-c3e4682a-24c1-4a90-805d-9ea9c4911afb.png)
改成始终返回true后试了下，获取状态全部没问题。👍
控制方面电源开关/温度调节也都没问题。只有整胆加热和半胆加热切换有问题，手动在热水器上设置整/半胆的话状态是能同步过来。
以下是手动在热水器上控制切换整/半胆加热后Homeassistant打印的日志：
···
2022-09-02 16:57:25.319 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Sending: {'header': 'aa0ce200000000000003', 'body': '0101', 'message type': '03', 'body type': '01'}
2022-09-02 16:57:25.592 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] aa18e200000000000003010109003c4600048000003c0000b6
2022-09-02 16:57:25.592 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.devices.e2.device] [17592187157846] Received: {'header': 'aa18e200000000000003', 'body': '010109003c4600048000003c0000', 'message type': '03', 'body type': '01'}
2022-09-02 16:57:25.593 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Status update: {'power': True, 'heating': False, 'heat_insulating': True, 'current_temperature': 60, 'target_temperature': 60, 'mode': 0, 'whole_tank_heating': False, 'variable_heating': False, 'protection': False, 'heating_power': 0, 'auto_cut_out': False}
2022-09-02 16:57:51.503 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] aa18e200000000000004010109003c4600088000003c0000b1
2022-09-02 16:57:51.504 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.devices.e2.device] [17592187157846] Received: {'header': 'aa18e200000000000004', 'body': '010109003c4600088000003c0000', 'message type': '04', 'body type': '01'}
2022-09-02 16:57:51.504 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Status update: {'power': True, 'heating': False, 'heat_insulating': True, 'current_temperature': 60, 'target_temperature': 60, 'mode': 0, 'whole_tank_heating': True, 'variable_heating': False, 'protection': False, 'heating_power': 0, 'auto_cut_out': False}
2022-09-02 16:57:53.515 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] aa18e200000000000004010109003c4600048000003c0000b5
2022-09-02 16:57:53.515 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.devices.e2.device] [17592187157846] Received: {'header': 'aa18e200000000000004', 'body': '010109003c4600048000003c0000', 'message type': '04', 'body type': '01'}
2022-09-02 16:57:53.516 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Status update: {'power': True, 'heating': False, 'heat_insulating': True, 'current_temperature': 60, 'target_temperature': 60, 'mode': 0, 'whole_tank_heating': False, 'variable_heating': False, 'protection': False, 'heating_power': 0, 'auto_cut_out': False}
2022-09-02 16:57:55.520 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] aa18e200000000000004010109003c4600088000003c0000b1
2022-09-02 16:57:55.520 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.devices.e2.device] [17592187157846] Received: {'header': 'aa18e200000000000004', 'body': '010109003c4600088000003c0000', 'message type': '04', 'body type': '01'}
2022-09-02 16:57:55.520 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Status update: {'power': True, 'heating': False, 'heat_insulating': True, 'current_temperature': 60, 'target_temperature': 60, 'mode': 0, 'whole_tank_heating': True, 'variable_heating': False, 'protection': False, 'heating_power': 0, 'auto_cut_out': False}
2022-09-02 16:58:25.554 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Sending: {'header': 'aa0ce200000000000003', 'body': '0101', 'message type': '03', 'body type': '01'}
2022-09-02 16:58:25.822 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] aa18e200000000000003010109003c4600088000003c0000b2
2022-09-02 16:58:25.822 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.devices.e2.device] [17592187157846] Received: {'header': 'aa18e200000000000003', 'body': '010109003c4600088000003c0000', 'message type': '03', 'body type': '01'}
2022-09-02 16:58:25.823 DEBUG (客卫的热水器) [custom_components.midea_ac_lan.midea.core.device] [17592187157846] Status update: {'power': True, 'heating': False, 'heat_insulating': True, 'current_temperature': 60, 'target_temperature': 60, 'mode': 0, 'whole_tank_heating': True, 'variable_heating': False, 'protection': False, 'heating_power': 0, 'auto_cut_out': False}
···

**Comment by georgezhao2010** [comment]
> ![image](https://user-images.githubusercontent.com/15974677/188104092-c3e4682a-24c1-4a90-805d-9ea9c4911afb.png) 改成始终返回true后试了下，获取状态全部没问题。👍 控制方面电源开关/温度调节也都没问题。只有整胆加热和半胆加热切换有问题，手动在热水器的面板上设置整/半胆的话状态是能同步过来的。 以下是手动在热水器上控制切换整/半胆加热后Homeassistant打印的日志：
> 
> ...

你加一下我QQ3325350呗，改完了你测试一下再发布
