### ISSUE TITLE
更新0.3.12后燃气热水器完全无法操作

### ISSUE THREAD

**Issue by micturkey** [georgezhao2010/midea_ac_lan#91]
热水器向ha的单项反馈是正常的，但是完全无法操作温度、开关，此前仅仅是无法操作温度，但是开关是正常的。
热水器型号：燃气热水器JSQ30-16HC4
HA报错信息：

> Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/midea_ac_lan/midea/devices/e3/device.py:89 
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22)) 
First occurred: 16:40:04 (1 occurrences) 
Last logged: 16:40:04

[547838122720] mode
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 993, in async_turn_off
    await self.hass.async_add_executor_job(ft.partial(self.turn_off, **kwargs))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/midea_ac_lan/switch.py", line 43, in turn_off
    self._device.set_attribute(attr=self._entity_key, value=False)
  File "/config/custom_components/midea_ac_lan/midea/devices/e3/device.py", line 89, in set_attribute
    DeviceAttributes.mode]:
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: mode

**Comment by micturkey** [comment]
定位到e3/device.py后发现是DeviceAttributes类中不存在mode，尝试把89、96、97三行注释掉后，开关、温度都正常了。
